### ISSUE TITLE
ToDo map: Just clicking Save on Edit ToDo should not change time range Event to all day

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mSuite#1616]
Screenshot Example of Event with time range

![calendar_map_switch_to_ToDo_with_Event_with_time_range](https://github.com/MicroHealthLLC/mSuite/assets/11938477/075d79b9-aec4-4c37-a583-7a9303d762a7)

Screenshot Example of Edit ToDo with time range, JUST click Save

![calendar_map_switch_to_ToDo_with_Event_with_time_range_click_edit_just_save](https://github.com/MicroHealthLLC/mSuite/assets/11938477/25809470-5e43-4622-8868-85564e96fd9d)

Screenshot Example of Dates displayed incorrectly

![calendar_map_switch_to_Calendar_after_edit-save_event_that_had_time-range](https://github.com/MicroHealthLLC/mSuite/assets/11938477/73e40df8-113a-41f2-9814-95c5c527456c)

Screenshot Example of Calendar with time range event automatically switched to all day event

![calendar_map_switch_to_Calendar_after_edit-save_event_that_had_time-range_2](https://github.com/MicroHealthLLC/mSuite/assets/11938477/aeefd715-6a21-41a9-865d-29f8048aae09)

**Comment by b-solution** [comment]
I fixed this issue, can you please test it again and let me know?

**Comment by LAlexMHllc** [comment]
Still needs to be fixed
Screenshot Example

![ToDo_edit_save_NOT_all-day-event_Switch_to_ToDo_changed_to_All_Day](https://github.com/MicroHealthLLC/mSuite/assets/11938477/ab174e75-8f6b-4b64-9a17-cf6cb6ab0ebf)

**Comment by b-solution** [comment]
Hi @LAlexMHllc, Hope you are doing well. Can you please test it again and let me know?

**Comment by MaxVMoons** [comment]
The time range issue is still not fixed, saving the task with a time range in the ToDo still transforms the task into an all day one.

**Comment by LAlexMHllc** [comment]
Still needs to be fixed. The Time Range did not change to All Day Event, but it still did not retain the original Start Time and End Time.
Screenshot Example

![calendar_with_time_range_Switch-to-ToDo__Save_Switch_to_Calendar](https://github.com/MicroHealthLLC/mSuite/assets/11938477/468a71ff-49e1-449a-b910-e296e2dc920e)

![calendar_with_time_range_Switch-to-ToDo__Save_Switch_to_Calendar_2](https://github.com/MicroHealthLLC/mSuite/assets/11938477/7a2fcd64-9d1e-4aec-a68d-7ace62b25eb3)

**Comment by LAlexMHllc** [comment]
Same issue for multi-day Event with Start Date and End Date.
Screenshot Example

![calendar_with_time_range_Switch-to-ToDo__Save_Switch_to_Calendar_3](https://github.com/MicroHealthLLC/mSuite/assets/11938477/27271f75-def5-4773-a52c-15439d831e8b)

![calendar_with_time_range_Switch-to-ToDo__Save_Switch_to_Calendar_4](https://github.com/MicroHealthLLC/mSuite/assets/11938477/bde96d12-7c2b-43d1-ae3b-3805ce1c8d0c)
